version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env  # ✅ Loads MongoDB URI safely
    volumes:
      - ./backend:/app
      - /app/node_modules  # Prevents unnecessary rebuilds

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents unnecessary rebuilds
